[package]
name = "zero_to_production"
version = "0.1.0"
authors = ["Viktor Kasimir <kasimir.viktor@gmail.com"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero_to_production"

[dependencies]
actix-web = "4"
env_logger = "0.9.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

